language: android  
android:
components:
- tools
- platform-tools
licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'
 
before_install:
  - chmod +x gradlew
 
script:  
  - ./gradlew assembleRelease
